<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.UNY9LSZ' shared service.

return $this->privates['.service_locator.UNY9LSZ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\BeatshareController::add' => ['privates', '.service_locator.Txvqv4R', 'get_ServiceLocator_Txvqv4RService.php', true],
    'App\\Controller\\BeatshareController::index' => ['privates', '.service_locator.hsWoe8a', 'get_ServiceLocator_HsWoe8aService.php', true],
    'App\\Controller\\BeatshareController::profil' => ['privates', '.service_locator.hsWoe8a', 'get_ServiceLocator_HsWoe8aService.php', true],
    'App\\Controller\\BeatshareController::removeBeat' => ['privates', '.service_locator.TfCNMP0', 'get_ServiceLocator_TfCNMP0Service.php', true],
    'App\\Controller\\SecurityController::account_modify' => ['privates', '.service_locator..paxKE7', 'get_ServiceLocator__PaxKE7Service.php', true],
    'App\\Controller\\SecurityController::deleteAccount' => ['privates', '.service_locator.zs05aVf', 'get_ServiceLocator_Zs05aVfService.php', true],
    'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.EbLunuf', 'get_ServiceLocator_EbLunufService.php', true],
    'App\\Controller\\SecurityController::registration' => ['privates', '.service_locator.czKK4py', 'get_ServiceLocator_CzKK4pyService.php', true],
    'App\\Controller\\BeatshareController:add' => ['privates', '.service_locator.Txvqv4R', 'get_ServiceLocator_Txvqv4RService.php', true],
    'App\\Controller\\BeatshareController:index' => ['privates', '.service_locator.hsWoe8a', 'get_ServiceLocator_HsWoe8aService.php', true],
    'App\\Controller\\BeatshareController:profil' => ['privates', '.service_locator.hsWoe8a', 'get_ServiceLocator_HsWoe8aService.php', true],
    'App\\Controller\\BeatshareController:removeBeat' => ['privates', '.service_locator.TfCNMP0', 'get_ServiceLocator_TfCNMP0Service.php', true],
    'App\\Controller\\SecurityController:account_modify' => ['privates', '.service_locator..paxKE7', 'get_ServiceLocator__PaxKE7Service.php', true],
    'App\\Controller\\SecurityController:deleteAccount' => ['privates', '.service_locator.zs05aVf', 'get_ServiceLocator_Zs05aVfService.php', true],
    'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.EbLunuf', 'get_ServiceLocator_EbLunufService.php', true],
    'App\\Controller\\SecurityController:registration' => ['privates', '.service_locator.czKK4py', 'get_ServiceLocator_CzKK4pyService.php', true],
], [
    'App\\Controller\\BeatshareController::add' => '?',
    'App\\Controller\\BeatshareController::index' => '?',
    'App\\Controller\\BeatshareController::profil' => '?',
    'App\\Controller\\BeatshareController::removeBeat' => '?',
    'App\\Controller\\SecurityController::account_modify' => '?',
    'App\\Controller\\SecurityController::deleteAccount' => '?',
    'App\\Controller\\SecurityController::login' => '?',
    'App\\Controller\\SecurityController::registration' => '?',
    'App\\Controller\\BeatshareController:add' => '?',
    'App\\Controller\\BeatshareController:index' => '?',
    'App\\Controller\\BeatshareController:profil' => '?',
    'App\\Controller\\BeatshareController:removeBeat' => '?',
    'App\\Controller\\SecurityController:account_modify' => '?',
    'App\\Controller\\SecurityController:deleteAccount' => '?',
    'App\\Controller\\SecurityController:login' => '?',
    'App\\Controller\\SecurityController:registration' => '?',
]);
