<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator..paxKE7' shared service.

return $this->privates['.service_locator..paxKE7'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'encoder' => ['services', 'security.password_encoder', 'getSecurity_PasswordEncoderService.php', true],
    'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
    'repo' => ['privates', 'App\\Repository\\ArticleRepository', 'getArticleRepositoryService.php', true],
], [
    'encoder' => '?',
    'manager' => '?',
    'repo' => 'App\\Repository\\ArticleRepository',
]);
